### ISSUE TITLE
How do I get my SteamID?

### ISSUE THREAD

**Issue by Unknow0059** [bburky/playnite-non-steam-shortcuts#15]
This "SteamID" must not be the same as my web profile's "SteamID" - which one can find by going to one's profile, viewing source, and grabbing the 17-character-long number - because this number is nowhere to be seen within Steam's entire directory tree.

~~So it's something else, and I don't know how to get that.~~

I managed to get it by traveling the opposite way from a game's appid directory. I still would like to know the "official" way.

Unrelated question: "The game in Playnite will be modified to launch the game using Steam."
Is Playnite aware of whether a game is running or not when the game's launched externally to it?

**Comment by bburky** [comment]
I think it's just the old style 8 digit steamID (not steamID3 or steamID64). I usually find the if by just looking under `C:\Program Files (x86)\Steam\userdata\...`.

From Playnite's perspective, it's launching the game by a `steam://` url, so playtime tracking is not guaranteed to work. I think playtime tracking works anyway if you've correctly configured the installation directory of the game sometimes though.

**Comment by Unknow0059** [comment]
> I usually find the id by just looking under `C:\Program Files (x86)\Steam\userdata\...`.

Yeah, I have more than one of those.

I guess I'll test whether the playtime tracking works and update this.

**Comment by Unknow0059** [comment]
It doesn't. You must start it from Playnite. So it is one-way - if you have the shortcuts on Steam you must use them from Playnite in order to get tracking.
