### ISSUE TITLE
Bug when importing

### ISSUE THREAD

**Issue by JamyPatch44** [bburky/playnite-non-steam-shortcuts#2]
Hi, I sometimes get this bug when importing games:

https://i.imgur.com/3rBhth1.png

It forces me to restart my PC or the extension won't work again. Any ideas what it may be please?

**Comment by bburky** [comment]
Oh... I know what causes this. I forgot that names of games can have Unicode characters. I'll try to fix this soon

**Comment by JamyPatch44** [comment]
Thank you! :)

**Comment by JamyPatch44** [comment]
Did you have any luck with this?

**Comment by JamyPatch44** [comment]
Did you have any luck with this please?

**Comment by bburky** [comment]
Sorry for completely ignoring my Playnite projects for a while, I saw your Reddit post and decided to fix this.

I just implemented a change in 855f36884aa348d99a671491507b049afe7dda87 to encode all strings as UTF-8. It looks like it works for me locally. I tested with some accented Unicode characters, and some emoji. Everything looks like it works.

Can you please [download an updated version of the extension](https://github.com/bburky/playnite-non-steam-shortcuts/archive/master.zip) and try it?

**Comment by JamyPatch44** [comment]
> Sorry for completely ignoring my Playnite projects for a while, I saw your Reddit post and decided to fix this.
> 
> I just implemented a change in [855f368](https://github.com/bburky/playnite-non-steam-shortcuts/commit/855f36884aa348d99a671491507b049afe7dda87) to encode all strings as UTF-8. It looks like it works for me locally. I tested with some accented Unicode characters, and some emoji. Everything looks like it works.
> 
> Can you please [download an updated version of the extension](https://github.com/bburky/playnite-non-steam-shortcuts/archive/master.zip) and try it?

Worked perfectly, thank you :)
