### ISSUE TITLE
Syntax for shortcutpath in nonsteam.py

### ISSUE THREAD

**Issue by JeffreySWhitmore** [bburky/playnite-non-steam-shortcuts#20]
Hi thanks for all this.
I don't understand the instructions.

By STEAMUSER DATA do you mean shortcutpath?
I have used this to no avail:
"shortcutpath": E:\Steam\userdata\82734948\config\shortcuts.vdf,
and 
"shortcutpath": E:\Steam\userdata\82734948\config\,
and 
"shortcutpath": E:\Steam\userdata\82734948,

In each instance "the extension is not loading properly."  
I have tried quotations on these as well to no avail, and i have heard there is a timeout so it may be hard to enter different values.
Am I missing something?

**Comment by bburky** [comment]
Did you get it to work? The correct path should be E:\Steam\userdata\82734948

The current version of the extension now uses a dialog to prompt you to select the folder. Navigate to the numbered userdata directory and click OK.

You can download the current version as a .pext from the releases page if you're still on an older version: https://github.com/bburky/playnite-non-steam-shortcuts/releases/latest
